;; Generic Brainfuck operations only. No Thread, dictionary, database or graph ABI.
(module
  (import "io" "memory" (memory 1))
  (import "io" "available" (func $available (result i32)))
  (import "io" "read" (func $read (result i32)))
  (import "io" "write" (func $write (param i32) (result i32)))
  (global $pc (export "pc") (mut i32) (i32.const 0))
  (global $p (export "pointer") (mut i32) (i32.const 0))
  (global $steps (export "steps") (mut f64) (f64.const 0))
  (global $blocks (export "blocks") (mut f64) (f64.const 0))
  (global $high (export "highWater") (mut i32) (i32.const 0))
  (global $cells (mut i32) (i32.const 0))
  (global $base (mut i32) (i32.const 0))
  (global $count (mut i32) (i32.const 0))
  (func (export "configure") (param $cells i32) (param $base i32) (param $count i32)
    (global.set $cells (local.get $cells))
    (global.set $base (local.get $base))
    (global.set $count (local.get $count)))
  (func $bounds (param $min i32) (param $max i32) (result i32)
    (local $hi i32)
    (local.set $hi (i32.add (global.get $p) (local.get $max)))
    (if (i32.or
          (i32.lt_s (i32.add (global.get $p) (local.get $min)) (i32.const 0))
          (i32.ge_s (local.get $hi) (global.get $cells)))
      (then (return (i32.const 1))))
    (if (i32.gt_s (local.get $hi) (global.get $high))
      (then (global.set $high (local.get $hi))))
    (i32.const 0))
  ;; Return: 0 halted, 1 waiting for input, 2 work budget, 3 bounds, 4 output cap.
  (func (export "run") (param $fuel f64) (param $work f64) (result i32)
    (local $limit f64) (local $worklimit f64) (local $cost f64)
    (local $op i32) (local $kind i32) (local $addr i32) (local $value i32)
    (local $n i32) (local $iterations i32) (local $next i32)
    (local $delta i32) (local $end i32) (local $target i32)
    (local.set $limit (f64.add (global.get $steps) (local.get $fuel)))
    (local.set $worklimit (f64.add (global.get $blocks) (local.get $work)))
    (block $done
      (loop $dispatch
        (br_if $done (i32.ge_u (global.get $pc) (global.get $count)))
        (local.set $op (i32.add (global.get $base) (i32.mul (global.get $pc) (i32.const 32))))
        (local.set $kind (i32.load (local.get $op)))
        (if (i32.eq (local.get $kind) (i32.const 5))
          (then
            (if (i32.eqz (call $available))
              (then (return (i32.const 1))))))
        (local.set $addr (i32.shl (global.get $p) (i32.const 1)))
        (local.set $value (i32.load16_u (local.get $addr)))
        (local.set $n (i32.load offset=4 (local.get $op)))
        (local.set $cost (f64.convert_i32_u (i32.load offset=8 (local.get $op))))
        (if (i32.eq (local.get $kind) (i32.const 2))
          (then
            (local.set $iterations (local.get $value))
            (if (i32.eq (local.get $n) (i32.const 1))
              (then (local.set $iterations (i32.and (i32.sub (i32.const 65536) (local.get $value)) (i32.const 65535)))))
            (local.set $cost (f64.add (f64.const 1) (f64.mul (local.get $cost) (f64.convert_i32_u (local.get $iterations)))))))
        (if (i32.or (f64.gt (f64.add (global.get $steps) (local.get $cost)) (local.get $limit))
                    (f64.ge (global.get $blocks) (local.get $worklimit)))
          (then (return (i32.const 2))))
        (global.set $steps (f64.add (global.get $steps) (local.get $cost)))
        (global.set $blocks (f64.add (global.get $blocks) (f64.const 1)))
        (local.set $next (i32.add (global.get $pc) (i32.const 1)))
        (if (i32.eq (local.get $kind) (i32.const 0))
          (then (i32.store16 (local.get $addr) (i32.add (local.get $value) (local.get $n)))))
        (if (i32.eq (local.get $kind) (i32.const 1))
          (then
            (if (call $bounds (i32.load offset=12 (local.get $op)) (i32.load offset=16 (local.get $op)))
              (then (return (i32.const 3))))
            (global.set $p (i32.add (global.get $p) (local.get $n)))))
        (if (i32.and (i32.eq (local.get $kind) (i32.const 2)) (i32.ne (local.get $iterations) (i32.const 0)))
          (then
            (if (call $bounds (i32.load offset=12 (local.get $op)) (i32.load offset=16 (local.get $op)))
              (then (return (i32.const 3))))
            (local.set $delta (i32.load offset=24 (local.get $op)))
            (local.set $end (i32.add (local.get $delta) (i32.mul (i32.load offset=28 (local.get $op)) (i32.const 8))))
            (block $applied
              (loop $apply
                (br_if $applied (i32.ge_u (local.get $delta) (local.get $end)))
                (local.set $target (i32.add (local.get $addr) (i32.shl (i32.load (local.get $delta)) (i32.const 1))))
                (i32.store16 (local.get $target)
                  (i32.add (i32.load16_u (local.get $target)) (i32.mul (local.get $iterations) (i32.load offset=4 (local.get $delta)))))
                (local.set $delta (i32.add (local.get $delta) (i32.const 8)))
                (br $apply)))))
        (if (i32.and (i32.eq (local.get $kind) (i32.const 3)) (i32.eqz (local.get $value)))
          (then (local.set $next (i32.load offset=20 (local.get $op)))))
        (if (i32.and (i32.eq (local.get $kind) (i32.const 4)) (i32.ne (local.get $value) (i32.const 0)))
          (then (local.set $next (i32.load offset=20 (local.get $op)))))
        (if (i32.eq (local.get $kind) (i32.const 5))
          (then (i32.store16 (local.get $addr) (call $read))))
        (if (i32.eq (local.get $kind) (i32.const 6))
          (then
            (if (call $write (i32.and (local.get $value) (i32.const 255)))
              (then
                (global.set $steps (f64.sub (global.get $steps) (local.get $cost)))
                (global.set $blocks (f64.sub (global.get $blocks) (f64.const 1)))
                (return (i32.const 4))))))
        (global.set $pc (local.get $next))
        (br $dispatch)))
    (i32.const 0))
)
